### PR TITLE
Adding other file types

### PR DESCRIPTION
**Pull request by wang-joseph**
# Description

Modified the script to search and sort video and audio files, and added common video/audio file formats.

Also added some other common formats for the other file types.

Related to #12 

## Have you read the [Contributing Guidelines](https://github.com/Kreateer/automatic-file-sorter/blob/master/CONTRIBUTING.md)?
*Put 'X' between the brackets to choose answer*

- [x] Yes
- [ ] No

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines ([PEP 8](https://pep8.org/)) of this project.
- [x] I have performed a self-review of my own code and have established there are no errors.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by wang-joseph** [comment]
I accidently added a few white spaces to .gitignore so I pushed another commit to remove them, sorry about that 😓

**Review by Kreateer — APPROVED** [review]
@EmeraldEntities Looks good to me 😄 Merging this with 'master'~

**Comment by wang-joseph** [comment]
@Kreateer Awesome! Can I join the super cool contributor section now 😉

**Comment by Kreateer** [comment]
@EmeraldEntities Haha of course, I'll update the files asap 😊 👍

**Comment by wang-joseph** [comment]
@Kreateer Haha awesome, thanks!

**Pull request merged**
